### ISSUE TITLE
Elements not working in Node 7.5.0?

### ISSUE THREAD

**Issue by Cristy94** [JosephusPaye/Keen-UI#231]
I installed `KeenUI` using `npm install keen-ui --save`, tried to add a `<ui-button>` element and I get these warnings and error:
```
[Vue warn]: Property or method "_c" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <ui-button> at C:\code\packages\keen-ui\src\UiButton.vue)
[Vue warn]: Property or method "_v" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <ui-button> at C:\code\packages\keen-ui\src\UiButton.vue)
Uncaught TypeError: _vm._v is not a function
```

I register all components globally:
```
import KeenUI from 'keen-ui';
Vue.use(KeenUI);
```

And in my template:
```
<ui-button>Test</ui-button>
```

Any suggestions?

**Comment by JosephusPaye** [comment]
Hi @Cristy94, 

Not sure why this is happening. Could you make a simple repo showing the issue?

**Comment by Cristy94** [comment]
I think there was a problem with some referenced packages. After running `npm update` everything works as expected. It's odd that my initial vue project installation was done a few weeks ago.

Anyway, for anyone who has this problem try running `npm update` and it should be fixed.
